site_name: DORIS Homepage

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: bottom
    navigation_depth: 4
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true

plugins:
    - search

markdown_extensions:
  - footnotes

nav:
    - DORIS Documentation: 
      - General Information: 'index.md'
      - DorisWeb (Web Version): 'doris-web.md'
      - Doris UI: 
        - General Information: 'doris-ui.md'
        - Supported File Formats:
          - JSON Format: 'json-format.md'
          - Tabular Format: 'csv-excel-format.md'
        - Using Doris UI: 'using-doris-ui.md'
      - Using DORIS from ICD-API: 'doris-api.md'
